per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1e-5
warmup_steps: 100
max_steps: 500
gradient_checkpointing: True
store_path : ${hydra:runtime.cwd}/runs/
configname : trainconfig